name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cv.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
