name: Build LaTeX documents
on:
  push:
    tags:
      - '*'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile cv
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv.tex
      - name: Compile grades
        uses: xu-cheng/latex-action@v2
        with:
          root_file: grades.tex
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 
            - "cv.pdf"
            - "grades.pdf"
          token: ${{ secrets.GITHUB_TOKEN }}
